const router = require('express').Router();
const authenticate = require('../middlewares/authenticate');
const requirePermission = require('../middlewares/requirePermission');
const requireTicketAccess = require('../middlewares/requireTicketAccess');
const upload = require('../middlewares/upload');
const { list, detail, getMessages, getOutboundOptions, assign, resolve, update, sendMessage, sendMediaMessage, reopen, summarize, deleteMessage, linkContact, forwardMessage, createNote } = require('../controllers/ticketController');
const { updatePreferences } = require('../controllers/ticketPreferencesController');
const auditEvent = require('../middlewares/auditEvent');
router.use(authenticate, requirePermission('inbox.view'));
router.get('/', list);
router.post('/', requirePermission('inbox.reopen'), auditEvent('TICKET_REOPEN', 'ticket'), reopen);
router.get('/:id', requireTicketAccess, detail);
router.get('/:id/outbound-options', requireTicketAccess, getOutboundOptions);
router.get('/:id/messages', requireTicketAccess, getMessages);
router.patch('/:id/preferences', requireTicketAccess, auditEvent('TICKET_PREFERENCES_UPDATE', 'ticket'), updatePreferences);
router.patch('/:id', requireTicketAccess, auditEvent('TICKET_UPDATE', 'ticket'), update);
router.patch('/:id/assign', requireTicketAccess, requirePermission('inbox.assign', 'inbox.transfer'), auditEvent('TICKET_ASSIGN', 'ticket'), assign);
router.patch('/:id/resolve', requireTicketAccess, requirePermission('inbox.resolve'), auditEvent('TICKET_RESOLVE', 'ticket'), resolve);
router.patch('/:id/link-contact', requireTicketAccess, auditEvent('TICKET_LINK_CONTACT', 'ticket'), linkContact);
router.post('/:id/messages', requireTicketAccess, auditEvent('TICKET_MESSAGE_SEND', 'ticket'), sendMessage);
router.post('/:id/media', requireTicketAccess, upload.single('file'), auditEvent('TICKET_MEDIA_SEND', 'ticket'), sendMediaMessage);
router.post('/:id/summarize', requireTicketAccess, auditEvent('TICKET_SUMMARIZE', 'ticket'), summarize);
router.post('/reopen', requirePermission('inbox.reopen'), auditEvent('TICKET_REOPEN', 'ticket'), reopen);
router.delete('/:id/messages/:messageId', requireTicketAccess, requirePermission('inbox.delete_message'), auditEvent('TICKET_MESSAGE_DELETE', 'ticket'), deleteMessage);
router.post('/:id/forward', requireTicketAccess, auditEvent('TICKET_MESSAGE_FORWARD', 'ticket'), forwardMessage);
router.post('/:id/notes', requireTicketAccess, auditEvent('TICKET_NOTE_CREATE', 'ticket'), createNote);

module.exports = router;
