ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "attendanceAvailable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "attendanceHeartbeatAt" TIMESTAMP(3);
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "slaPolicyKey" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "slaWarnedAt" TIMESTAMP(3);
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "slaBreachedAt" TIMESTAMP(3);
CREATE TABLE IF NOT EXISTS "AttendancePolicy" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "tenantId" TEXT NOT NULL UNIQUE REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "slaEnabled" BOOLEAN NOT NULL DEFAULT false,
  "assignmentEnabled" BOOLEAN NOT NULL DEFAULT false,
  "redistributeUnavailable" BOOLEAN NOT NULL DEFAULT false,
  "maxActiveTickets" INTEGER NOT NULL DEFAULT 10,
  "unavailableMinutes" INTEGER NOT NULL DEFAULT 5,
  "rules" JSONB NOT NULL DEFAULT '[]',
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
